// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BZcFhxpKql0a5dIppUbL_KSeqtmKt6A',
    appId: '1:127908056948:web:dd4229842a78d5dd97a621',
    messagingSenderId: '127908056948',
    projectId: 'playemdata',
    authDomain: 'playemdata.firebaseapp.com',
    storageBucket: 'playemdata.firebasestorage.app',
    measurementId: 'G-R5ML2RWXLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6A7qcZ3ET12i-Yk9uz9hcUlM4-vT4Dik',
    appId: '1:127908056948:android:8a1d2e7e4752dd8a97a621',
    messagingSenderId: '127908056948',
    projectId: 'playemdata',
    storageBucket: 'playemdata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOuDYWDlwdkSt7jDMKAzpQKUJnCm9_8Y',
    appId: '1:127908056948:ios:f337d01bb2e6065397a621',
    messagingSenderId: '127908056948',
    projectId: 'playemdata',
    storageBucket: 'playemdata.firebasestorage.app',
    iosBundleId: 'com.example.playem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChOuDYWDlwdkSt7jDMKAzpQKUJnCm9_8Y',
    appId: '1:127908056948:ios:f337d01bb2e6065397a621',
    messagingSenderId: '127908056948',
    projectId: 'playemdata',
    storageBucket: 'playemdata.firebasestorage.app',
    iosBundleId: 'com.example.playem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8BZcFhxpKql0a5dIppUbL_KSeqtmKt6A',
    appId: '1:127908056948:web:aa396d56ce59ca4897a621',
    messagingSenderId: '127908056948',
    projectId: 'playemdata',
    authDomain: 'playemdata.firebaseapp.com',
    storageBucket: 'playemdata.firebasestorage.app',
    measurementId: 'G-BME3PXCR8S',
  );
}
